### ISSUE TITLE
dosn work

### ISSUE THREAD

**Issue by marvinborner** [LarsVomMars/yadwf#1]
idk why. just say "error"

**Comment by marvinborner** [comment]
o fixt it: just do `nmp isntalt''

**Comment by LarsVomMars** [comment]
Nice

**Comment by marvinborner** [comment]
opss, its not fixt anymoar! it sas "fail" alwas..

**Comment by marvinborner** [comment]
on se otha hand its fixed i thynkk

**Comment by LarsVomMars** [comment]
sat freus me
